// AUTO-GENERATED by scripts/gen_runway_manifest.py — do not edit by hand.
// Clean runway-end list per airport (from OSM aeroway data), used by the
// home page's active-runway picker.
export interface RunwayEnd { name: string; hdg: number; }
export interface RunwayPair { ref: string; ends: [RunwayEnd, RunwayEnd]; lengthFt: number; }
export const RUNWAY_MANIFEST: Record<string, RunwayPair[]> = {
  "EGLL": [
    {
      "ref": "09L/27R",
      "ends": [
        {
          "name": "09L",
          "hdg": 90
        },
        {
          "name": "27R",
          "hdg": 270
        }
      ],
      "lengthFt": 11755
    },
    {
      "ref": "09R/27L",
      "ends": [
        {
          "name": "27L",
          "hdg": 90
        },
        {
          "name": "09R",
          "hdg": 270
        }
      ],
      "lengthFt": 10970
    }
  ],
  "KLAX": [
    {
      "ref": "07L/25R",
      "ends": [
        {
          "name": "07L",
          "hdg": 83
        },
        {
          "name": "25R",
          "hdg": 263
        }
      ],
      "lengthFt": 11103
    },
    {
      "ref": "07R/25L",
      "ends": [
        {
          "name": "07R",
          "hdg": 83
        },
        {
          "name": "25L",
          "hdg": 263
        }
      ],
      "lengthFt": 11070
    },
    {
      "ref": "06R/24L",
      "ends": [
        {
          "name": "06R",
          "hdg": 83
        },
        {
          "name": "24L",
          "hdg": 263
        }
      ],
      "lengthFt": 10324
    },
    {
      "ref": "06L/24R",
      "ends": [
        {
          "name": "06L",
          "hdg": 83
        },
        {
          "name": "24R",
          "hdg": 263
        }
      ],
      "lengthFt": 8907
    }
  ],
  "KJFK": [
    {
      "ref": "13R/31L",
      "ends": [
        {
          "name": "13R",
          "hdg": 121
        },
        {
          "name": "31L",
          "hdg": 301
        }
      ],
      "lengthFt": 14487
    },
    {
      "ref": "04L/22R",
      "ends": [
        {
          "name": "22R",
          "hdg": 31
        },
        {
          "name": "04L",
          "hdg": 211
        }
      ],
      "lengthFt": 12080
    },
    {
      "ref": "13L/31R",
      "ends": [
        {
          "name": "31R",
          "hdg": 121
        },
        {
          "name": "13L",
          "hdg": 301
        }
      ],
      "lengthFt": 8957
    },
    {
      "ref": "04R/22L",
      "ends": [
        {
          "name": "04R",
          "hdg": 31
        },
        {
          "name": "22L",
          "hdg": 211
        }
      ],
      "lengthFt": 8401
    }
  ],
  "KSFO": [
    {
      "ref": "10L/28R",
      "ends": [
        {
          "name": "28R",
          "hdg": 118
        },
        {
          "name": "10L",
          "hdg": 298
        }
      ],
      "lengthFt": 11545
    },
    {
      "ref": "10R/28L",
      "ends": [
        {
          "name": "28L",
          "hdg": 118
        },
        {
          "name": "10R",
          "hdg": 298
        }
      ],
      "lengthFt": 11061
    },
    {
      "ref": "01R/19L",
      "ends": [
        {
          "name": "01R",
          "hdg": 28
        },
        {
          "name": "19L",
          "hdg": 208
        }
      ],
      "lengthFt": 8086
    },
    {
      "ref": "01L/19R",
      "ends": [
        {
          "name": "19R",
          "hdg": 28
        },
        {
          "name": "01L",
          "hdg": 208
        }
      ],
      "lengthFt": 7021
    }
  ],
  "KBOS": [
    {
      "ref": "15R/33L",
      "ends": [
        {
          "name": "15R",
          "hdg": 135
        },
        {
          "name": "33L",
          "hdg": 315
        }
      ],
      "lengthFt": 9190
    },
    {
      "ref": "4R/22L",
      "ends": [
        {
          "name": "4R",
          "hdg": 20
        },
        {
          "name": "22L",
          "hdg": 200
        }
      ],
      "lengthFt": 7646
    },
    {
      "ref": "4L/22R",
      "ends": [
        {
          "name": "22R",
          "hdg": 20
        },
        {
          "name": "4L",
          "hdg": 200
        }
      ],
      "lengthFt": 7034
    },
    {
      "ref": "09/27",
      "ends": [
        {
          "name": "09",
          "hdg": 76
        },
        {
          "name": "27",
          "hdg": 256
        }
      ],
      "lengthFt": 6982
    },
    {
      "ref": "14/32",
      "ends": [
        {
          "name": "14",
          "hdg": 126
        },
        {
          "name": "32",
          "hdg": 306
        }
      ],
      "lengthFt": 4982
    }
  ],
  "VIDP": [
    {
      "ref": "10/28",
      "ends": [
        {
          "name": "28",
          "hdg": 105
        },
        {
          "name": "10",
          "hdg": 285
        }
      ],
      "lengthFt": 12493
    },
    {
      "ref": "11L/29R",
      "ends": [
        {
          "name": "29R",
          "hdg": 104
        },
        {
          "name": "11L",
          "hdg": 284
        }
      ],
      "lengthFt": 9849
    },
    {
      "ref": "09/27",
      "ends": [
        {
          "name": "27",
          "hdg": 91
        },
        {
          "name": "09",
          "hdg": 271
        }
      ],
      "lengthFt": 8725
    },
    {
      "ref": "11R/29L",
      "ends": [
        {
          "name": "29L",
          "hdg": 104
        },
        {
          "name": "11R",
          "hdg": 284
        }
      ],
      "lengthFt": 7631
    }
  ]
};
