// AUTO-GENERATED by scripts/gen_runway_manifest.py — do not edit by hand.
// Clean runway-end list per airport (from OSM aeroway data), used by the
// home page's active-runway picker and the engine's runway-state bootstrap.
// Ends are oriented by geometry (designator ×10 vs magnetic bearing from that
// end toward the other); `hdg` is the TRUE heading of movement from `thr`
// (the physical end of the pavement) toward the far end.
export interface RunwayEnd { name: string; hdg: number; thr: { lat: number; lng: number }; lengthFt: number; }
export interface RunwayPair { ref: string; ends: [RunwayEnd, RunwayEnd]; lengthFt: number; }
export const RUNWAY_MANIFEST: Record<string, RunwayPair[]> = {
  "EGLL": [
    {
      "ref": "09L/27R",
      "ends": [
        {
          "name": "09L",
          "hdg": 89.6,
          "thr": {
            "lat": 51.4774783,
            "lng": -0.4894255
          },
          "lengthFt": 12755
        },
        {
          "name": "27R",
          "hdg": 269.6,
          "thr": {
            "lat": 51.4776791,
            "lng": -0.4332975
          },
          "lengthFt": 12755
        }
      ],
      "lengthFt": 12755
    },
    {
      "ref": "09R/27L",
      "ends": [
        {
          "name": "27L",
          "hdg": 269.7,
          "thr": {
            "lat": 51.4649463,
            "lng": -0.4340796
          },
          "lengthFt": 11967
        },
        {
          "name": "09R",
          "hdg": 89.7,
          "thr": {
            "lat": 51.4647721,
            "lng": -0.4867392
          },
          "lengthFt": 11967
        }
      ],
      "lengthFt": 11967
    }
  ],
  "KLAX": [
    {
      "ref": "07L/25R",
      "ends": [
        {
          "name": "07L",
          "hdg": 83.0,
          "thr": {
            "lat": 33.9355566,
            "lng": -118.4220858
          },
          "lengthFt": 12896
        },
        {
          "name": "25R",
          "hdg": 263.0,
          "thr": {
            "lat": 33.9398827,
            "lng": -118.3797944
          },
          "lengthFt": 12896
        }
      ],
      "lengthFt": 12896
    },
    {
      "ref": "07R/25L",
      "ends": [
        {
          "name": "07R",
          "hdg": 83.0,
          "thr": {
            "lat": 33.9336567,
            "lng": -118.41902
          },
          "lengthFt": 11069
        },
        {
          "name": "25L",
          "hdg": 263.0,
          "thr": {
            "lat": 33.9373692,
            "lng": -118.3827215
          },
          "lengthFt": 11069
        }
      ],
      "lengthFt": 11069
    },
    {
      "ref": "06R/24L",
      "ends": [
        {
          "name": "06R",
          "hdg": 82.9,
          "thr": {
            "lat": 33.9468183,
            "lng": -118.434692
          },
          "lengthFt": 10866
        },
        {
          "name": "24L",
          "hdg": 262.9,
          "thr": {
            "lat": 33.9504688,
            "lng": -118.399059
          },
          "lengthFt": 10866
        }
      ],
      "lengthFt": 10866
    },
    {
      "ref": "06L/24R",
      "ends": [
        {
          "name": "06L",
          "hdg": 82.9,
          "thr": {
            "lat": 33.9491177,
            "lng": -118.4311801
          },
          "lengthFt": 8908
        },
        {
          "name": "24R",
          "hdg": 262.9,
          "thr": {
            "lat": 33.9521114,
            "lng": -118.4019676
          },
          "lengthFt": 8908
        }
      ],
      "lengthFt": 8908
    }
  ],
  "KJFK": [
    {
      "ref": "13R/31L",
      "ends": [
        {
          "name": "13R",
          "hdg": 120.8,
          "thr": {
            "lat": 40.6483674,
            "lng": -73.816711
          },
          "lengthFt": 14487
        },
        {
          "name": "31L",
          "hdg": 300.8,
          "thr": {
            "lat": 40.6280016,
            "lng": -73.7717843
          },
          "lengthFt": 14487
        }
      ],
      "lengthFt": 14487
    },
    {
      "ref": "04L/22R",
      "ends": [
        {
          "name": "22R",
          "hdg": 210.7,
          "thr": {
            "lat": 40.6505148,
            "lng": -73.7633228
          },
          "lengthFt": 12080
        },
        {
          "name": "04L",
          "hdg": 30.7,
          "thr": {
            "lat": 40.6220346,
            "lng": -73.7855848
          },
          "lengthFt": 12080
        }
      ],
      "lengthFt": 12080
    },
    {
      "ref": "13L/31R",
      "ends": [
        {
          "name": "31R",
          "hdg": 300.9,
          "thr": {
            "lat": 40.6437308,
            "lng": -73.7592669
          },
          "lengthFt": 9987
        },
        {
          "name": "13L",
          "hdg": 120.9,
          "thr": {
            "lat": 40.6577735,
            "lng": -73.7902373
          },
          "lengthFt": 9987
        }
      ],
      "lengthFt": 9987
    },
    {
      "ref": "04R/22L",
      "ends": [
        {
          "name": "04R",
          "hdg": 30.7,
          "thr": {
            "lat": 40.6254357,
            "lng": -73.7703494
          },
          "lengthFt": 8401
        },
        {
          "name": "22L",
          "hdg": 210.7,
          "thr": {
            "lat": 40.6452432,
            "lng": -73.7548683
          },
          "lengthFt": 8401
        }
      ],
      "lengthFt": 8401
    }
  ],
  "KSFO": [
    {
      "ref": "10L/28R",
      "ends": [
        {
          "name": "28R",
          "hdg": 297.9,
          "thr": {
            "lat": 37.6135221,
            "lng": -122.3571268
          },
          "lengthFt": 11859
        },
        {
          "name": "10L",
          "hdg": 117.9,
          "thr": {
            "lat": 37.6287384,
            "lng": -122.3933957
          },
          "lengthFt": 11859
        }
      ],
      "lengthFt": 11859
    },
    {
      "ref": "10R/28L",
      "ends": [
        {
          "name": "28L",
          "hdg": 297.9,
          "thr": {
            "lat": 37.6117118,
            "lng": -122.3583623
          },
          "lengthFt": 11356
        },
        {
          "name": "10R",
          "hdg": 117.9,
          "thr": {
            "lat": 37.6262806,
            "lng": -122.3930936
          },
          "lengthFt": 11356
        }
      ],
      "lengthFt": 11356
    },
    {
      "ref": "01R/19L",
      "ends": [
        {
          "name": "01R",
          "hdg": 27.7,
          "thr": {
            "lat": 37.6063429,
            "lng": -122.3810695
          },
          "lengthFt": 8648
        },
        {
          "name": "19L",
          "hdg": 207.7,
          "thr": {
            "lat": 37.6273238,
            "lng": -122.3671391
          },
          "lengthFt": 8648
        }
      ],
      "lengthFt": 8648
    },
    {
      "ref": "01L/19R",
      "ends": [
        {
          "name": "19R",
          "hdg": 207.7,
          "thr": {
            "lat": 37.6265018,
            "lng": -122.3706186
          },
          "lengthFt": 7696
        },
        {
          "name": "01L",
          "hdg": 27.7,
          "thr": {
            "lat": 37.6078248,
            "lng": -122.3830042
          },
          "lengthFt": 7696
        }
      ],
      "lengthFt": 7696
    }
  ],
  "KBOS": [
    {
      "ref": "15R/33L",
      "ends": [
        {
          "name": "15R",
          "hdg": 135.3,
          "thr": {
            "lat": 42.3742782,
            "lng": -71.0178919
          },
          "lengthFt": 10076
        },
        {
          "name": "33L",
          "hdg": 315.3,
          "thr": {
            "lat": 42.3546592,
            "lng": -70.9915828
          },
          "lengthFt": 10076
        }
      ],
      "lengthFt": 10076
    },
    {
      "ref": "4R/22L",
      "ends": [
        {
          "name": "4R",
          "hdg": 19.7,
          "thr": {
            "lat": 42.3510507,
            "lng": -71.0117953
          },
          "lengthFt": 10014
        },
        {
          "name": "22L",
          "hdg": 199.7,
          "thr": {
            "lat": 42.376899,
            "lng": -70.9992944
          },
          "lengthFt": 10014
        }
      ],
      "lengthFt": 10014
    },
    {
      "ref": "4L/22R",
      "ends": [
        {
          "name": "22R",
          "hdg": 199.7,
          "thr": {
            "lat": 42.3782995,
            "lng": -71.0045071
          },
          "lengthFt": 8000
        },
        {
          "name": "4L",
          "hdg": 19.7,
          "thr": {
            "lat": 42.3576498,
            "lng": -71.0145005
          },
          "lengthFt": 8000
        }
      ],
      "lengthFt": 8000
    },
    {
      "ref": "09/27",
      "ends": [
        {
          "name": "09",
          "hdg": 76.5,
          "thr": {
            "lat": 42.3557464,
            "lng": -71.0128869
          },
          "lengthFt": 6982
        },
        {
          "name": "27",
          "hdg": 256.5,
          "thr": {
            "lat": 42.3602139,
            "lng": -70.987701
          },
          "lengthFt": 6982
        }
      ],
      "lengthFt": 6982
    },
    {
      "ref": "14/32",
      "ends": [
        {
          "name": "14",
          "hdg": 125.8,
          "thr": {
            "lat": 42.3565946,
            "lng": -71.0232559
          },
          "lengthFt": 4982
        },
        {
          "name": "32",
          "hdg": 305.8,
          "thr": {
            "lat": 42.3486084,
            "lng": -71.0082647
          },
          "lengthFt": 4982
        }
      ],
      "lengthFt": 4982
    }
  ],
  "VIDP": [
    {
      "ref": "11R/29L",
      "ends": [
        {
          "name": "29L",
          "hdg": 283.7,
          "thr": {
            "lat": 28.5377405,
            "lng": 77.1094816
          },
          "lengthFt": 14506
        },
        {
          "name": "11R",
          "hdg": 103.7,
          "thr": {
            "lat": 28.5471776,
            "lng": 77.065506
          },
          "lengthFt": 14506
        }
      ],
      "lengthFt": 14506
    },
    {
      "ref": "11L/29R",
      "ends": [
        {
          "name": "29R",
          "hdg": 283.7,
          "thr": {
            "lat": 28.540758,
            "lng": 77.1118545
          },
          "lengthFt": 14447
        },
        {
          "name": "11L",
          "hdg": 103.7,
          "thr": {
            "lat": 28.550145,
            "lng": 77.068052
          },
          "lengthFt": 14447
        }
      ],
      "lengthFt": 14447
    },
    {
      "ref": "10/28",
      "ends": [
        {
          "name": "28",
          "hdg": 284.7,
          "thr": {
            "lat": 28.5585512,
            "lng": 77.1225627
          },
          "lengthFt": 12493
        },
        {
          "name": "10",
          "hdg": 104.7,
          "thr": {
            "lat": 28.5672434,
            "lng": 77.0848508
          },
          "lengthFt": 12493
        }
      ],
      "lengthFt": 12493
    },
    {
      "ref": "09/27",
      "ends": [
        {
          "name": "27",
          "hdg": 271.5,
          "thr": {
            "lat": 28.569907,
            "lng": 77.1168831
          },
          "lengthFt": 9222
        },
        {
          "name": "09",
          "hdg": 91.5,
          "thr": {
            "lat": 28.5705565,
            "lng": 77.0881138
          },
          "lengthFt": 9222
        }
      ],
      "lengthFt": 9222
    }
  ]
};

/** Look up a runway end by name (case-insensitive) across an airport's manifest. */
export function manifestEnd(icao: string, name: string): { pair: RunwayPair; end: RunwayEnd; other: RunwayEnd } | null {
  const N = name.toUpperCase();
  for (const pair of RUNWAY_MANIFEST[icao] ?? []) {
    const i = pair.ends.findIndex(e => e.name.toUpperCase() === N);
    if (i >= 0) return { pair, end: pair.ends[i], other: pair.ends[1 - i] };
  }
  return null;
}
