// AUTO-GENERATED by scripts/gen_runway_manifest.py — do not edit by hand.
// Clean runway-end list per airport (from OSM aeroway data), used by the
// home page's active-runway picker and the engine's runway-state bootstrap.
// Ends are oriented by geometry (designator ×10 vs magnetic bearing from that
// end toward the other); `hdg` is the TRUE heading of movement from `thr`
// (the physical end of the pavement) toward the far end.
export interface RunwayEnd { name: string; hdg: number; thr: { lat: number; lng: number }; lengthFt: number; }
export interface RunwayPair { ref: string; ends: [RunwayEnd, RunwayEnd]; lengthFt: number; }
export const RUNWAY_MANIFEST: Record<string, RunwayPair[]> = {
  "EGLL": [
    {
      "ref": "09L/27R",
      "ends": [
        {
          "name": "09L",
          "hdg": 89.6,
          "thr": {
            "lat": 51.4774783,
            "lng": -0.4894255
          },
          "lengthFt": 12755
        },
        {
          "name": "27R",
          "hdg": 269.6,
          "thr": {
            "lat": 51.4776791,
            "lng": -0.4332975
          },
          "lengthFt": 12755
        }
      ],
      "lengthFt": 12755
    },
    {
      "ref": "09R/27L",
      "ends": [
        {
          "name": "27L",
          "hdg": 269.7,
          "thr": {
            "lat": 51.4649463,
            "lng": -0.4340796
          },
          "lengthFt": 11967
        },
        {
          "name": "09R",
          "hdg": 89.7,
          "thr": {
            "lat": 51.4647721,
            "lng": -0.4867392
          },
          "lengthFt": 11967
        }
      ],
      "lengthFt": 11967
    }
  ],
  "KLAX": [
    {
      "ref": "07L/25R",
      "ends": [
        {
          "name": "07L",
          "hdg": 83.0,
          "thr": {
            "lat": 33.9355566,
            "lng": -118.4220858
          },
          "lengthFt": 12896
        },
        {
          "name": "25R",
          "hdg": 263.0,
          "thr": {
            "lat": 33.9398827,
            "lng": -118.3797944
          },
          "lengthFt": 12896
        }
      ],
      "lengthFt": 12896
    },
    {
      "ref": "07R/25L",
      "ends": [
        {
          "name": "07R",
          "hdg": 83.0,
          "thr": {
            "lat": 33.9336567,
            "lng": -118.41902
          },
          "lengthFt": 11069
        },
        {
          "name": "25L",
          "hdg": 263.0,
          "thr": {
            "lat": 33.9373692,
            "lng": -118.3827215
          },
          "lengthFt": 11069
        }
      ],
      "lengthFt": 11069
    },
    {
      "ref": "06R/24L",
      "ends": [
        {
          "name": "06R",
          "hdg": 82.9,
          "thr": {
            "lat": 33.9468183,
            "lng": -118.434692
          },
          "lengthFt": 10866
        },
        {
          "name": "24L",
          "hdg": 262.9,
          "thr": {
            "lat": 33.9504688,
            "lng": -118.399059
          },
          "lengthFt": 10866
        }
      ],
      "lengthFt": 10866
    },
    {
      "ref": "06L/24R",
      "ends": [
        {
          "name": "06L",
          "hdg": 82.9,
          "thr": {
            "lat": 33.9491177,
            "lng": -118.4311801
          },
          "lengthFt": 8908
        },
        {
          "name": "24R",
          "hdg": 262.9,
          "thr": {
            "lat": 33.9521114,
            "lng": -118.4019676
          },
          "lengthFt": 8908
        }
      ],
      "lengthFt": 8908
    }
  ],
  "KJFK": [
    {
      "ref": "13R/31L",
      "ends": [
        {
          "name": "13R",
          "hdg": 120.8,
          "thr": {
            "lat": 40.6483674,
            "lng": -73.816711
          },
          "lengthFt": 14487
        },
        {
          "name": "31L",
          "hdg": 300.8,
          "thr": {
            "lat": 40.6280016,
            "lng": -73.7717843
          },
          "lengthFt": 14487
        }
      ],
      "lengthFt": 14487
    },
    {
      "ref": "04L/22R",
      "ends": [
        {
          "name": "22R",
          "hdg": 210.7,
          "thr": {
            "lat": 40.6505148,
            "lng": -73.7633228
          },
          "lengthFt": 12080
        },
        {
          "name": "04L",
          "hdg": 30.7,
          "thr": {
            "lat": 40.6220346,
            "lng": -73.7855848
          },
          "lengthFt": 12080
        }
      ],
      "lengthFt": 12080
    },
    {
      "ref": "13L/31R",
      "ends": [
        {
          "name": "31R",
          "hdg": 300.9,
          "thr": {
            "lat": 40.6437308,
            "lng": -73.7592669
          },
          "lengthFt": 9987
        },
        {
          "name": "13L",
          "hdg": 120.9,
          "thr": {
            "lat": 40.6577735,
            "lng": -73.7902373
          },
          "lengthFt": 9987
        }
      ],
      "lengthFt": 9987
    },
    {
      "ref": "04R/22L",
      "ends": [
        {
          "name": "04R",
          "hdg": 30.7,
          "thr": {
            "lat": 40.6254357,
            "lng": -73.7703494
          },
          "lengthFt": 8401
        },
        {
          "name": "22L",
          "hdg": 210.7,
          "thr": {
            "lat": 40.6452432,
            "lng": -73.7548683
          },
          "lengthFt": 8401
        }
      ],
      "lengthFt": 8401
    }
  ],
  "KSFO": [
    {
      "ref": "10L/28R",
      "ends": [
        {
          "name": "28R",
          "hdg": 297.9,
          "thr": {
            "lat": 37.6135221,
            "lng": -122.3571268
          },
          "lengthFt": 11859
        },
        {
          "name": "10L",
          "hdg": 117.9,
          "thr": {
            "lat": 37.6287384,
            "lng": -122.3933957
          },
          "lengthFt": 11859
        }
      ],
      "lengthFt": 11859
    },
    {
      "ref": "10R/28L",
      "ends": [
        {
          "name": "28L",
          "hdg": 297.9,
          "thr": {
            "lat": 37.6117118,
            "lng": -122.3583623
          },
          "lengthFt": 11356
        },
        {
          "name": "10R",
          "hdg": 117.9,
          "thr": {
            "lat": 37.6262806,
            "lng": -122.3930936
          },
          "lengthFt": 11356
        }
      ],
      "lengthFt": 11356
    },
    {
      "ref": "01R/19L",
      "ends": [
        {
          "name": "01R",
          "hdg": 27.7,
          "thr": {
            "lat": 37.6063429,
            "lng": -122.3810695
          },
          "lengthFt": 8648
        },
        {
          "name": "19L",
          "hdg": 207.7,
          "thr": {
            "lat": 37.6273238,
            "lng": -122.3671391
          },
          "lengthFt": 8648
        }
      ],
      "lengthFt": 8648
    },
    {
      "ref": "01L/19R",
      "ends": [
        {
          "name": "19R",
          "hdg": 207.7,
          "thr": {
            "lat": 37.6265018,
            "lng": -122.3706186
          },
          "lengthFt": 7696
        },
        {
          "name": "01L",
          "hdg": 27.7,
          "thr": {
            "lat": 37.6078248,
            "lng": -122.3830042
          },
          "lengthFt": 7696
        }
      ],
      "lengthFt": 7696
    }
  ],
  "KBOS": [
    {
      "ref": "15R/33L",
      "ends": [
        {
          "name": "15R",
          "hdg": 135.3,
          "thr": {
            "lat": 42.3742782,
            "lng": -71.0178919
          },
          "lengthFt": 10076
        },
        {
          "name": "33L",
          "hdg": 315.3,
          "thr": {
            "lat": 42.3546592,
            "lng": -70.9915828
          },
          "lengthFt": 10076
        }
      ],
      "lengthFt": 10076
    },
    {
      "ref": "4R/22L",
      "ends": [
        {
          "name": "4R",
          "hdg": 19.7,
          "thr": {
            "lat": 42.3510507,
            "lng": -71.0117953
          },
          "lengthFt": 10014
        },
        {
          "name": "22L",
          "hdg": 199.7,
          "thr": {
            "lat": 42.376899,
            "lng": -70.9992944
          },
          "lengthFt": 10014
        }
      ],
      "lengthFt": 10014
    },
    {
      "ref": "4L/22R",
      "ends": [
        {
          "name": "22R",
          "hdg": 199.7,
          "thr": {
            "lat": 42.3782995,
            "lng": -71.0045071
          },
          "lengthFt": 8000
        },
        {
          "name": "4L",
          "hdg": 19.7,
          "thr": {
            "lat": 42.3576498,
            "lng": -71.0145005
          },
          "lengthFt": 8000
        }
      ],
      "lengthFt": 8000
    },
    {
      "ref": "09/27",
      "ends": [
        {
          "name": "09",
          "hdg": 76.5,
          "thr": {
            "lat": 42.3557464,
            "lng": -71.0128869
          },
          "lengthFt": 6982
        },
        {
          "name": "27",
          "hdg": 256.5,
          "thr": {
            "lat": 42.3602139,
            "lng": -70.987701
          },
          "lengthFt": 6982
        }
      ],
      "lengthFt": 6982
    },
    {
      "ref": "14/32",
      "ends": [
        {
          "name": "14",
          "hdg": 125.8,
          "thr": {
            "lat": 42.3565946,
            "lng": -71.0232559
          },
          "lengthFt": 4982
        },
        {
          "name": "32",
          "hdg": 305.8,
          "thr": {
            "lat": 42.3486084,
            "lng": -71.0082647
          },
          "lengthFt": 4982
        }
      ],
      "lengthFt": 4982
    }
  ],
  "VIDP": [
    {
      "ref": "11R/29L",
      "ends": [
        {
          "name": "29L",
          "hdg": 283.7,
          "thr": {
            "lat": 28.5377405,
            "lng": 77.1094816
          },
          "lengthFt": 14506
        },
        {
          "name": "11R",
          "hdg": 103.7,
          "thr": {
            "lat": 28.5471776,
            "lng": 77.065506
          },
          "lengthFt": 14506
        }
      ],
      "lengthFt": 14506
    },
    {
      "ref": "11L/29R",
      "ends": [
        {
          "name": "29R",
          "hdg": 283.7,
          "thr": {
            "lat": 28.540758,
            "lng": 77.1118545
          },
          "lengthFt": 14447
        },
        {
          "name": "11L",
          "hdg": 103.7,
          "thr": {
            "lat": 28.550145,
            "lng": 77.068052
          },
          "lengthFt": 14447
        }
      ],
      "lengthFt": 14447
    },
    {
      "ref": "10/28",
      "ends": [
        {
          "name": "28",
          "hdg": 284.7,
          "thr": {
            "lat": 28.5585512,
            "lng": 77.1225627
          },
          "lengthFt": 12493
        },
        {
          "name": "10",
          "hdg": 104.7,
          "thr": {
            "lat": 28.5672434,
            "lng": 77.0848508
          },
          "lengthFt": 12493
        }
      ],
      "lengthFt": 12493
    },
    {
      "ref": "09/27",
      "ends": [
        {
          "name": "27",
          "hdg": 271.5,
          "thr": {
            "lat": 28.569907,
            "lng": 77.1168831
          },
          "lengthFt": 9222
        },
        {
          "name": "09",
          "hdg": 91.5,
          "thr": {
            "lat": 28.5705565,
            "lng": 77.0881138
          },
          "lengthFt": 9222
        }
      ],
      "lengthFt": 9222
    }
  ],
  "VHHH": [
    {
      "ref": "07C/25C",
      "ends": [
        {
          "name": "07C",
          "hdg": 70.8,
          "thr": {
            "lat": 22.3095087,
            "lng": 113.8936028
          },
          "lengthFt": 13849
        },
        {
          "name": "25C",
          "hdg": 250.8,
          "thr": {
            "lat": 22.3219943,
            "lng": 113.9323517
          },
          "lengthFt": 13849
        }
      ],
      "lengthFt": 13849
    },
    {
      "ref": "07L/25R",
      "ends": [
        {
          "name": "07L",
          "hdg": 70.8,
          "thr": {
            "lat": 22.3210705,
            "lng": 113.8806988
          },
          "lengthFt": 13028
        },
        {
          "name": "25R",
          "hdg": 250.8,
          "thr": {
            "lat": 22.3328187,
            "lng": 113.91715
          },
          "lengthFt": 13028
        }
      ],
      "lengthFt": 13028
    },
    {
      "ref": "07R/25L",
      "ends": [
        {
          "name": "07R",
          "hdg": 70.8,
          "thr": {
            "lat": 22.2962344,
            "lng": 113.8979744
          },
          "lengthFt": 12453
        },
        {
          "name": "25L",
          "hdg": 250.8,
          "thr": {
            "lat": 22.3074689,
            "lng": 113.9328156
          },
          "lengthFt": 12453
        }
      ],
      "lengthFt": 12453
    }
  ],
  "YSSY": [
    {
      "ref": "16R/34L",
      "ends": [
        {
          "name": "16R",
          "hdg": 167.8,
          "thr": {
            "lat": -33.9293647,
            "lng": 151.1715713
          },
          "lengthFt": 13023
        },
        {
          "name": "34L",
          "hdg": 347.8,
          "thr": {
            "lat": -33.9642591,
            "lng": 151.1806465
          },
          "lengthFt": 13023
        }
      ],
      "lengthFt": 13023
    },
    {
      "ref": "07/25",
      "ends": [
        {
          "name": "07",
          "hdg": 74.1,
          "thr": {
            "lat": -33.9437501,
            "lng": 151.163637
          },
          "lengthFt": 7934
        },
        {
          "name": "25",
          "hdg": 254.1,
          "thr": {
            "lat": -33.9377961,
            "lng": 151.1888513
          },
          "lengthFt": 7934
        }
      ],
      "lengthFt": 7934
    },
    {
      "ref": "16L/34R",
      "ends": [
        {
          "name": "16L",
          "hdg": 167.9,
          "thr": {
            "lat": -33.9496066,
            "lng": 151.1883124
          },
          "lengthFt": 7890
        },
        {
          "name": "34R",
          "hdg": 347.9,
          "thr": {
            "lat": -33.9707536,
            "lng": 151.1937817
          },
          "lengthFt": 7890
        }
      ],
      "lengthFt": 7890
    }
  ],
  "LFPG": [
    {
      "ref": "09R/27L",
      "ends": [
        {
          "name": "09R",
          "hdg": 85.3,
          "thr": {
            "lat": 49.0206191,
            "lng": 2.5130694
          },
          "lengthFt": 13732
        },
        {
          "name": "27L",
          "hdg": 265.3,
          "thr": {
            "lat": 49.0236896,
            "lng": 2.5702633
          },
          "lengthFt": 13732
        }
      ],
      "lengthFt": 13732
    },
    {
      "ref": "08L/26R",
      "ends": [
        {
          "name": "08L",
          "hdg": 85.3,
          "thr": {
            "lat": 48.9956867,
            "lng": 2.5527456
          },
          "lengthFt": 13562
        },
        {
          "name": "26R",
          "hdg": 265.3,
          "thr": {
            "lat": 48.9987075,
            "lng": 2.6092344
          },
          "lengthFt": 13562
        }
      ],
      "lengthFt": 13562
    },
    {
      "ref": "09L/27R",
      "ends": [
        {
          "name": "27R",
          "hdg": 265.4,
          "thr": {
            "lat": 49.026687,
            "lng": 2.5616864
          },
          "lengthFt": 8836
        },
        {
          "name": "09L",
          "hdg": 85.4,
          "thr": {
            "lat": 49.0247313,
            "lng": 2.5248814
          },
          "lengthFt": 8836
        }
      ],
      "lengthFt": 8836
    },
    {
      "ref": "08R/26L",
      "ends": [
        {
          "name": "08R",
          "hdg": 85.3,
          "thr": {
            "lat": 48.9929148,
            "lng": 2.5656415
          },
          "lengthFt": 8834
        },
        {
          "name": "26L",
          "hdg": 265.3,
          "thr": {
            "lat": 48.9948831,
            "lng": 2.6024373
          },
          "lengthFt": 8834
        }
      ],
      "lengthFt": 8834
    }
  ],
  "WSSS": [
    {
      "ref": "02R/20L",
      "ends": [
        {
          "name": "02R",
          "hdg": 22.9,
          "thr": {
            "lat": 1.3223944,
            "lng": 103.9998434
          },
          "lengthFt": 13378
        },
        {
          "name": "20L",
          "hdg": 202.9,
          "thr": {
            "lat": 1.3561785,
            "lng": 104.0141068
          },
          "lengthFt": 13378
        }
      ],
      "lengthFt": 13378
    },
    {
      "ref": "03/21",
      "ends": [
        {
          "name": "03",
          "hdg": 22.9,
          "thr": {
            "lat": 1.315353,
            "lng": 104.0125409
          },
          "lengthFt": 13207
        },
        {
          "name": "21",
          "hdg": 202.9,
          "thr": {
            "lat": 1.3487047,
            "lng": 104.0266227
          },
          "lengthFt": 13207
        }
      ],
      "lengthFt": 13207
    },
    {
      "ref": "02L/20R",
      "ends": [
        {
          "name": "20R",
          "hdg": 202.9,
          "thr": {
            "lat": 1.3822403,
            "lng": 103.9914946
          },
          "lengthFt": 13178
        },
        {
          "name": "02L",
          "hdg": 22.9,
          "thr": {
            "lat": 1.348954,
            "lng": 103.9774596
          },
          "lengthFt": 13178
        }
      ],
      "lengthFt": 13178
    },
    {
      "ref": "02C/20C",
      "ends": [
        {
          "name": "02C",
          "hdg": 22.9,
          "thr": {
            "lat": 1.3287993,
            "lng": 103.9849668
          },
          "lengthFt": 13127
        },
        {
          "name": "20C",
          "hdg": 202.9,
          "thr": {
            "lat": 1.3619499,
            "lng": 103.9989657
          },
          "lengthFt": 13127
        }
      ],
      "lengthFt": 13127
    }
  ],
  "RJTT": [
    {
      "ref": "16L/34R",
      "ends": [
        {
          "name": "34R",
          "hdg": 330.0,
          "thr": {
            "lat": 35.5392315,
            "lng": 139.805462
          },
          "lengthFt": 11415
        },
        {
          "name": "16L",
          "hdg": 150.0,
          "thr": {
            "lat": 35.5663276,
            "lng": 139.7862316
          },
          "lengthFt": 11415
        }
      ],
      "lengthFt": 11415
    },
    {
      "ref": "16R/34L",
      "ends": [
        {
          "name": "34L",
          "hdg": 330.0,
          "thr": {
            "lat": 35.5366291,
            "lng": 139.7856418
          },
          "lengthFt": 9983
        },
        {
          "name": "16R",
          "hdg": 150.0,
          "thr": {
            "lat": 35.560327,
            "lng": 139.7688258
          },
          "lengthFt": 9983
        }
      ],
      "lengthFt": 9983
    },
    {
      "ref": "04/22",
      "ends": [
        {
          "name": "22",
          "hdg": 214.9,
          "thr": {
            "lat": 35.5679034,
            "lng": 139.7774913
          },
          "lengthFt": 8606
        },
        {
          "name": "04",
          "hdg": 34.9,
          "thr": {
            "lat": 35.5485649,
            "lng": 139.7608889
          },
          "lengthFt": 8606
        }
      ],
      "lengthFt": 8606
    },
    {
      "ref": "05/23",
      "ends": [
        {
          "name": "05",
          "hdg": 42.4,
          "thr": {
            "lat": 35.523996,
            "lng": 139.8034708
          },
          "lengthFt": 8174
        },
        {
          "name": "23",
          "hdg": 222.4,
          "thr": {
            "lat": 35.5405363,
            "lng": 139.82205
          },
          "lengthFt": 8174
        }
      ],
      "lengthFt": 8174
    }
  ],
  "OMDB": [
    {
      "ref": "12R/30L",
      "ends": [
        {
          "name": "30L",
          "hdg": 301.5,
          "thr": {
            "lat": 25.2353515,
            "lng": 55.3958753
          },
          "lengthFt": 14546
        },
        {
          "name": "12R",
          "hdg": 121.5,
          "thr": {
            "lat": 25.2561974,
            "lng": 55.3582935
          },
          "lengthFt": 14546
        }
      ],
      "lengthFt": 14546
    },
    {
      "ref": "12L/30R",
      "ends": [
        {
          "name": "12L",
          "hdg": 121.5,
          "thr": {
            "lat": 25.2667249,
            "lng": 55.3466213
          },
          "lengthFt": 14252
        },
        {
          "name": "30R",
          "hdg": 301.5,
          "thr": {
            "lat": 25.2462962,
            "lng": 55.3834414
          },
          "lengthFt": 14252
        }
      ],
      "lengthFt": 14252
    }
  ]
};

/** Look up a runway end by name (case-insensitive) across an airport's manifest. */
export function manifestEnd(icao: string, name: string): { pair: RunwayPair; end: RunwayEnd; other: RunwayEnd } | null {
  const N = name.toUpperCase();
  for (const pair of RUNWAY_MANIFEST[icao] ?? []) {
    const i = pair.ends.findIndex(e => e.name.toUpperCase() === N);
    if (i >= 0) return { pair, end: pair.ends[i], other: pair.ends[1 - i] };
  }
  return null;
}
