// AUTO-GENERATED by scripts/fetch_satellite.py — do not edit by hand.
// Bounding boxes (EPSG:4326) for the pre-baked static satellite images in
// public/maps/satellite/{ICAO}.jpg, used as MapLibre `image` sources so the
// ground view never refetches tiles while zooming/panning.
// `wide*` is the soft, far-padded backdrop drawn beneath the detail image so
// a pitched 3D camera sees terrain instead of the detail image's hard edge.
export interface SatBounds {
  minLng: number; minLat: number; maxLng: number; maxLat: number;
  wideMinLng: number; wideMinLat: number; wideMaxLng: number; wideMaxLat: number;
}
export const SATELLITE_BOUNDS: Record<string, SatBounds> = {
  EGLL: { minLng: -0.517098505, minLat: 51.449394575, maxLng: -0.38956739500000004, maxLat: 51.485012125000004, wideMinLng: -0.7909153, wideMinLat: 51.37292159999999, wideMaxLng: -0.11575060000000009, wideMaxLat: 51.56148510000001 },
  KLAX: { minLng: -118.45518065, minLat: 33.924232685, maxLng: -118.35950975, maxLat: 33.959339215, wideMinLng: -118.66059170000004, wideMinLat: 33.8488569, wideMaxLng: -118.15409869999996, wideMaxLat: 34.034715 },
  KJFK: { minLng: -73.84665291, minLat: 40.607255115, maxLng: -73.73107229, maxLat: 40.679041184999996, wideMinLng: -74.09481130000003, wideMinLat: 40.45312620000001, wideMaxLng: -73.48291389999997, wideMaxLat: 40.83317009999999 },
  KSFO: { minLng: -122.414803425, minLat: 37.59329455, maxLng: -122.34142207500001, maxLat: 37.65011025, wideMinLng: -122.57235750000001, wideMinLat: 37.47130790000001, wideMaxLng: -122.183868, wideMaxLat: 37.77209689999999 },
  KBOS: { minLng: -71.07474792, minLat: 42.33817819000001, maxLng: -70.96513328, maxLat: 42.38883920999999, wideMinLng: -71.31009699999997, wideMinLat: 42.229406000000026, wideMaxLng: -70.72978420000003, wideMaxLat: 42.497611399999975 },
  VIDP: { minLng: 77.044614685, minLat: 28.522495470000003, maxLng: 77.14313461500001, maxLat: 28.592307329999997, wideMinLng: 76.83308659999999, wideMinLat: 28.372605300000007, wideMaxLng: 77.35466270000002, wideMaxLat: 28.742197499999993 },
  VHHH: { minLng: 113.85994590000001, minLat: 22.28154921, maxLng: 113.96074569999999, maxLat: 22.34611079, wideMinLng: 113.64352280000003, wideMinLat: 22.142931700000005, wideMaxLng: 114.17716879999998, wideMaxLat: 22.484728299999997 },
  YSSY: { minLng: 151.08217446, minLat: -34.014722674999994, maxLng: 151.26726774, maxLat: -33.851498025000005, wideMinLng: 150.6847683000001, wideMinLat: -34.36517559999998, wideMaxLng: 151.6646738999999, wideMaxLat: -33.50104510000002 },
  LFPG: { minLng: 2.45112116, minLat: 48.961577350000006, maxLng: 2.65543464, maxLat: 49.09896625, wideMinLng: 2.0124481000000007, wideMinLat: 48.66659530000002, wideMaxLng: 3.0941076999999995, wideMaxLat: 49.393948299999984 },
  WSSS: { minLng: 103.925198955, minLat: 1.28191947, maxLng: 104.052917745, maxLat: 1.43498713, wideMinLng: 103.65097919999997, wideMinLat: 0.9532742000000001, wideMaxLng: 104.32713750000003, wideMaxLat: 1.7636324 },
  RJTT: { minLng: 139.7273691, minLat: 35.508373645, maxLng: 139.84659689999998, maxLat: 35.584253655, wideMinLng: 139.47138, wideMinLat: 35.345454799999985, wideMaxLng: 140.10258599999997, wideMaxLat: 35.74717250000001 },
  OMDB: { minLng: 55.316184189999994, minLat: 25.217600125000004, maxLng: 55.425083810000004, maxLat: 25.281840574999997, wideMinLng: 55.08237029999999, wideMinLat: 25.07967210000001, wideMaxLng: 55.65889770000001, wideMaxLat: 25.41976859999999 },
};
