services:
  skycontrol:
    container_name: skycontrol
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:3000"
    environment:
      - NODE_ENV=production
    networks:
      - skycontrol-net

networks:
  skycontrol-net:
    driver: bridge
