import { test } from 'node:test';
import { makeEngine, run, runUntil, cmd, byCs } from '../../tests/engine/helpers';
import { makeAst } from '../../src/lib/sim/commandAst';

test('probe departure lifecycle at EGLL', () => {
  const e = makeEngine('EGLL', { ends: ['27R', '27L'] });
  console.log('runways', e.runways.map(r => `${r.name}:${Math.round(r.headingTrue)} holds=${r.holdNodes.length}`).join(' '));
  console.log('gates', e.gates.length, 'stands', e.air.stands.length, 'holds', e.air.holdingPositions.length);
  const a = e.spawnDeparture({ callsign: 'BAW117', type: 'A320', runway: '27R' })!;
  console.log('spawned', a.callsign, a.phase, a.plan.gateRef, 'needsPush', a.needsPushback, 'hdg', Math.round(a.heading), 'pos', a.pos);
  const r = runUntil(e, () => a.requests.length > 0, 120);
  console.log('request after', r.elapsed, a.requests[0]?.kind, a.requests[0]?.text);
  let o = cmd(e, makeAst('pushback', 'BAW117', { dir: 'any', expectRunway: '27R', startup: true }));
  console.log('pushback', o);
  const r2 = runUntil(e, () => a.phase === 'startup' && a.pushback.stage === 'complete', 300);
  console.log('push complete', r2.ok, r2.elapsed, 'pos', a.pos, 'hdg', Math.round(a.heading), 'pushedM', Math.round(a.pushback.totalM));
  const r3 = runUntil(e, () => a.startup.enginesStable, 400);
  console.log('engines stable', r3.ok, r3.elapsed);
  const r4 = runUntil(e, () => a.requests[0]?.kind === 'taxi', 60);
  console.log('taxi req', r4.ok, r4.elapsed);
  o = cmd(e, makeAst('taxi', 'BAW117', { dest: { kind: 'runway', runway: '27R', intersection: null } }));
  console.log('taxi', o);
  const r5 = runUntil(e, () => a.phase === 'taxi', 30);
  console.log('taxi start', r5.ok, r5.elapsed, 'route', a.plan.taxiRoute, 'holds', a.path?.holds?.map(h => `${h.runway}@${Math.round(h.at)}${h.isDepartureEntry ? 'D' : ''}`), 'total', Math.round(a.path?.total ?? 0));
  const r6 = runUntil(e, () => a.phase === 'hold_short', 900);
  console.log('hold_short', r6.ok, r6.elapsed, 'node', a.holdShortNode, 'rwy', a.holdShortRunway, 'stage', e.stageOf(a), 'speed', a.speed.toFixed(1), 'dist to rwy', Math.round(e.distToRunway(a.pos, e.runwayState('27R')!.ref)));
  const evs = e.events.filter(ev => ['reached_hold', 'request', 'handoff'].includes(ev.type)).map(ev => `${ev.at.toFixed(0)} ${ev.type} ${ev.message}`);
  console.log(evs.slice(-6));
  const r7 = runUntil(e, () => a.onFrequency === 'tower' && a.requests[0]?.kind === 'ready', 60);
  console.log('ready', r7.ok, r7.elapsed, a.onFrequency);
  o = cmd(e, makeAst('takeoff', 'BAW117', { runway: '27R', afterDepHdg: null, initialAlt: 5000 }));
  console.log('takeoff', o);
  const r8 = runUntil(e, () => a.phase === 'takeoff', 30);
  console.log('rolling phase', r8.ok, r8.elapsed);
  const r9 = runUntil(e, () => a.delay.airborneAt != null, 120);
  console.log('airborne', r9.ok, r9.elapsed, 'spd', a.speed.toFixed(0));
  const r10 = runUntil(e, () => a.onFrequency === 'departure', 200);
  console.log('handoff to departure', r10.ok, r10.elapsed, 'alt', a.altitude.toFixed(0), 'phase', a.phase, 'stage', e.stageOf(a));
  console.log('score', e.stats.points, 'ledger', e.stats.ledger.map(l => l.code));
});
