#!/usr/bin/env python3
"""Emit src/lib/runwayManifest.ts — clean runway-end list per airport (from OSM
geojson), used by the home page's active-runway picker and the engine's
runway-state bootstrap.

Runway merging and end orientation come from scripts/osm_runways.py, which
mirrors src/lib/osmAirport.ts (the end whose designator ×10 matches the
magnetic bearing FROM that end TO the other end gets that name). The manifest
therefore agrees with the runtime graph: tests/data/airportData.test.ts
cross-checks both.

Runways shorter than 3000 ft (GA strips such as KBOS 15L/33R) are left out of
the picker; they remain in OsmAirport.runways for taxi routing.
"""
import json, os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from osm_runways import runways_for, MAGVAR_FALLBACK  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AIRPORTS = ['EGLL', 'KLAX', 'KJFK', 'KSFO', 'KBOS', 'VIDP', 'VHHH', 'YSSY', 'LFPG', 'WSSS', 'RJTT', 'OMDB']
MIN_LENGTH_FT = 3000


def manifest_for(icao):
    out = []
    for rw in runways_for(icao, MAGVAR_FALLBACK.get(icao)):
        length_ft = round(rw['lengthM'] * 3.28084)
        if length_ft < MIN_LENGTH_FT:
            print(f'   {icao} {rw["ref"]}: {length_ft} ft < {MIN_LENGTH_FT} ft, left out of the picker')
            continue
        if rw['ambiguous']:
            print(f'!! {icao} {rw["ref"]}: AMBIGUOUS orientation — check the OSM data')
        ends = []
        for e in rw['ends']:
            ends.append({'name': e['name'], 'hdg': round(e['hdg'], 1),
                         'thr': {'lat': round(e['lat'], 7), 'lng': round(e['lng'], 7)},
                         'lengthFt': length_ft})
        out.append({'ref': rw['ref'], 'ends': ends, 'lengthFt': length_ft})
    return out


manifest = {icao: manifest_for(icao) for icao in AIRPORTS}

ts_path = os.path.join(ROOT, 'src', 'lib', 'runwayManifest.ts')
lines = [
    '// AUTO-GENERATED by scripts/gen_runway_manifest.py — do not edit by hand.',
    '// Clean runway-end list per airport (from OSM aeroway data), used by the',
    '// home page\'s active-runway picker and the engine\'s runway-state bootstrap.',
    '// Ends are oriented by geometry (designator ×10 vs magnetic bearing from that',
    '// end toward the other); `hdg` is the TRUE heading of movement from `thr`',
    '// (the physical end of the pavement) toward the far end.',
    'export interface RunwayEnd { name: string; hdg: number; thr: { lat: number; lng: number }; lengthFt: number; }',
    'export interface RunwayPair { ref: string; ends: [RunwayEnd, RunwayEnd]; lengthFt: number; }',
    'export const RUNWAY_MANIFEST: Record<string, RunwayPair[]> = ' + json.dumps(manifest, indent=2) + ';',
    '',
    '/** Look up a runway end by name (case-insensitive) across an airport\'s manifest. */',
    'export function manifestEnd(icao: string, name: string): { pair: RunwayPair; end: RunwayEnd; other: RunwayEnd } | null {',
    '  const N = name.toUpperCase();',
    '  for (const pair of RUNWAY_MANIFEST[icao] ?? []) {',
    '    const i = pair.ends.findIndex(e => e.name.toUpperCase() === N);',
    '    if (i >= 0) return { pair, end: pair.ends[i], other: pair.ends[1 - i] };',
    '  }',
    '  return null;',
    '}',
]
with open(ts_path, 'w') as f:
    f.write('\n'.join(lines) + '\n')

for icao, rws in manifest.items():
    print(f'{icao}: {len(rws)} runway pairs -> ' + ', '.join(f"{r['ends'][0]['name']}({r['ends'][0]['hdg']})/{r['ends'][1]['name']}({r['ends'][1]['hdg']})" for r in rws))
print(f'\nWrote {ts_path}')
