#!/usr/bin/env python3
"""Emit src/lib/runwayManifest.ts — clean runway-end list per airport (from OSM
geojson), used by the new home page's active-runway picker."""
import json, math, os

def bearing(lng1, lat1, lng2, lat2):
    d2r = math.pi / 180
    dlng = (lng2 - lng1) * d2r
    lat1r, lat2r = lat1 * d2r, lat2 * d2r
    y = math.sin(dlng) * math.cos(lat2r)
    x = math.cos(lat1r) * math.sin(lat2r) - math.sin(lat1r) * math.cos(lat2r) * math.cos(dlng)
    return (math.atan2(y, x) * 180 / math.pi + 360) % 360

def dist_m(lng1, lat1, lng2, lat2):
    R = 6371000
    d2r = math.pi / 180
    dlat = (lat2 - lat1) * d2r
    dlng = (lng2 - lng1) * d2r
    mid = (lat1 + lat2) / 2 * d2r
    return math.hypot(dlat * R, dlng * R * math.cos(mid))

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OSM_DIR = os.path.join(ROOT, 'public', 'maps', 'osm')
AIRPORTS = ['EGLL', 'KLAX', 'KJFK', 'KSFO', 'KBOS', 'VIDP']

def runways_for(icao):
    path = os.path.join(OSM_DIR, f'{icao}.geojson')
    if not os.path.exists(path):
        return []
    with open(path) as f:
        d = json.load(f)
    seen = set()
    out = []
    for ft in d['features']:
        p = ft.get('properties') or {}
        ref = p.get('ref') or ''
        g = ft['geometry']
        if g['type'] != 'LineString' or '/' not in ref or ref.count('/') != 1:
            continue
        parts = ref.split('/')
        def is_rwy_name(s):
            s = s.strip()
            digits = ''.join(c for c in s if c.isdigit())
            return bool(digits) and 1 <= int(digits) <= 36
        if not is_rwy_name(parts[0]) or not is_rwy_name(parts[1]):
            continue
        coords = g['coordinates']
        c0, c1 = coords[0], coords[-1]
        key = f"{c0[0]:.5f},{c0[1]:.5f},{c1[0]:.5f},{c1[1]:.5f}"
        if key in seen:
            continue
        length_m = dist_m(c0[0], c0[1], c1[0], c1[1])
        length_ft = round(length_m * 3.28084)
        if length_ft < 3000:
            continue
        seen.add(key)
        hdg_fwd = bearing(c0[0], c0[1], c1[0], c1[1])
        def rwy_num(s): return int(''.join(c for c in s if c.isdigit()))
        n0, n1 = rwy_num(parts[0]), rwy_num(parts[1])
        diff0 = min(abs(n0*10 - hdg_fwd), abs(n0*10 - hdg_fwd + 360), abs(n0*10 - hdg_fwd - 360))
        diff1 = min(abs(n1*10 - hdg_fwd), abs(n1*10 - hdg_fwd + 360), abs(n1*10 - hdg_fwd - 360))
        if diff0 < diff1:
            e0, e1, h0, h1 = parts[0], parts[1], hdg_fwd, (hdg_fwd + 180) % 360
        else:
            e0, e1, h0, h1 = parts[1], parts[0], (hdg_fwd + 180) % 360, hdg_fwd
        out.append({'ref': ref, 'ends': [
            {'name': e0, 'hdg': round(h0)}, {'name': e1, 'hdg': round(h1)},
        ], 'lengthFt': length_ft})
    out.sort(key=lambda r: -r['lengthFt'])
    return out

manifest = {icao: runways_for(icao) for icao in AIRPORTS}

ts_path = os.path.join(ROOT, 'src', 'lib', 'runwayManifest.ts')
lines = [
    '// AUTO-GENERATED by scripts/gen_runway_manifest.py — do not edit by hand.',
    '// Clean runway-end list per airport (from OSM aeroway data), used by the',
    '// home page\'s active-runway picker.',
    'export interface RunwayEnd { name: string; hdg: number; }',
    'export interface RunwayPair { ref: string; ends: [RunwayEnd, RunwayEnd]; lengthFt: number; }',
    'export const RUNWAY_MANIFEST: Record<string, RunwayPair[]> = ' + json.dumps(manifest, indent=2) + ';',
]
with open(ts_path, 'w') as f:
    f.write('\n'.join(lines) + '\n')

for icao, rws in manifest.items():
    print(f'{icao}: {len(rws)} runway pairs -> {[r["ref"] for r in rws]}')
print(f'\nWrote {ts_path}')
